swagger: '2.0'
info:
  description: |
    
  version: 1.0.0
  title: 享实习API
  contact:
    email: chenye94@qq.com
host: localhost:8080
basePath: /api
schemes:
 - http
consumes:
  - application/json
produces:
  - application/json
tags:
- name: student
  description: All about student
- name: company
  description: All about company
- name: other
  description: Other apis
paths:
  /students:
    post:
      tags:
      - student
      summary: 学生注册
      parameters:
      - in: body
        name: student
        description: 注册学生的信息
        required: true
        schema:
          $ref: '#/definitions/Student'
      responses:
        200:
          description: 注册成功
          schema:
            $ref: '#/definitions/Student'
        403:
          description: 注册失败，手机号已被注册
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request, invalid arguments

  /students/login:
    post:
      tags:
      - student
      summary: 学生登录
      parameters:
      - in: body
        name: account
        description: 登录信息
        required: true
        schema:
          $ref: '#/definitions/BasicAccount'
      responses:
        200:
          description: 登录成功，返回学生信息
          schema:
            $ref: '#/definitions/Student'
        403:
          description: 登录失败，账号不存在或密码错误
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request, invalid arguments

  /students/{studentId}:
    get:
      tags:
      - student
      summary: 获取学生信息
      parameters:
      - in: path
        name: studentId
        description: 学生Id，若当前登录为学生的账号，只能获取自己的信息，可以设置为0。
        required: true
        type: integer
      responses:
        200:
          description: 成功，返回对应学生信息
          schema:
            $ref: '#/definitions/Student'
        400:
          description: Bad request, invalid arguments
        401:
          description: 当前未登录
        403:
          description: 获取失败，权限不允许
        404:
          description: 获取失败，此学生不存在
          schema:
            $ref: '#/definitions/Error'

  /companies:
    post:
      tags:
      - company
      summary: 企业注册
      parameters:
      - in: body
        name: company
        description: 注册企业的信息
        required: true
        schema:
          $ref: '#/definitions/Company'
      responses:
        200:
          description: 注册成功
          schema:
            $ref: '#/definitions/Company'
        403:
          description: 注册失败，手机号已被注册
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request, invalid arguments
  
  /companies/login:
    post:
      tags:
      - company
      summary: 企业登录
      parameters:
      - in: body
        name: account
        description: 登录信息
        required: true
        schema:
          $ref: '#/definitions/BasicAccount'
      responses:
        200:
          description: 登录成功，返回企业信息
          schema:
            $ref: '#/definitions/Company'
        403:
          description: 登录失败，账号不存在或密码错误
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request, invalid arguments

  /companies/{companyId}:
    get:
      tags:
      - company
      summary: 获取企业信息
      parameters:
      - in: path
        name: companyId
        description: 企业Id，若当前登录为企业的账号，只能获取自己的信息，可以设置为0。
        required: true
        type: integer
      responses:
        200:
          description: 成功，返回对应企业信息
          schema:
            $ref: '#/definitions/Company'
        400:
          description: Bad request, invalid arguments
        401:
          description: 当前未登录
        403:
          description: 获取失败，权限不允许
        404:
          description: 获取失败，此企业不存在
          schema:
            $ref: '#/definitions/Error'

  /upload/{type}:
    post:
      tags:
      - other
      summary: 上传照片
      consumes:
         - multipart/form-data
      parameters:
      - in: path
        name: type
        type: string
        enum:
          - STU_AVATAR
          - STU_CARD
          - STU_CERT
          - COMPANY_LOGO
          - COMPANY_CERT
          - OTHER
        required: true
        description: 照片分类  
      - in: formData
        name: file
        type: file
        description: 要上传的照片文件
      responses:
        200:
          description: 成功，返回上传结果
          schema:
            $ref: '#/definitions/UploadResult'
        400:
          description: Bad request, invalid arguments
        401:
          description: 当前未登录
          schema:
            $ref: '#/definitions/Error'

definitions:

  BasicModel:
    type: object
    properties:
      id:
        type: integer
        example: 123
        readOnly: true

  AccModel:
    type: object
    properties:
      accountId:
        type: integer
        example: 456
        readOnly: true
      account:
        $ref: '#/definitions/BasicAccount'

  BasicAccount:
    type: object
    required: 
      - phone
      - password
    properties:
      phone:
        type: string
        description: 登录手机号
        example: '18810203423'

      password:
        type: string
        description: 登录密码
        example: 'password'

  Account:
    type: object
    allOf: 
      - $ref: '#/definitions/BasicAccount'
      - $ref: '#/definitions/BasicModel'
      - properties:
          role:
            type: string
            description: 账号类型
            enum: 
              - 'ADMIN'
              - 'COMPANY'
              - 'STUDENT'
            example: 'COMPANY'
          wechat:
            type: string
            description: wechat oauth id
            example: 'gdalkdsowkdcasdfa'

  CompanyUpdater:
    type: object
    properties:
      name:
        type: string
        example: 'Google Inc.'
        description: 公司名
      addr:
        type: string
        example: 'No123 Bake Street'
        description: 公司地址
      type:
        type: string
        example: '民营'
        description: 公司性质
      scale:
        type: string
        example: 'scale'
        description: 公司规模
      contact:
        type: string
        description: 公司联系人
      contactPhone:
        type: string
        description: 联系人电话
      email:
        type: string
        description: HR邮箱
      phone:
        type: string
        description: 公司电话
      industry:
        type: string
        description: 公司所属行业
      code:
        type: string
        description: 统一社会信用代码
      intro:
        type: string
        description: 公司简介
    
  Company:
    allOf: 
      - $ref: '#/definitions/BasicModel'
      - $ref: '#/definitions/AccModel'
      - $ref: '#/definitions/CompanyUpdater'
     
  StudentUpdater:
    type: object
    properties:
      name:
        type: string
        example: 'Ye'
        description: 姓名
      phone:
        type: string
        description: 电话
      gender:
        type: string
        description: 性别
        enum: 
          - MALE
          - FEMALE
      education:
        type: string
        description: 学历
        enum:
          - COLLEGE
          - BACHELOR
          - MASTER
          - PHD
      major:
        type: string
        description: 专业
      area:
        type: string
        description: 区域
      email:
        type: string
        description: 邮箱
      school:
        type: string
        description: 学校
      language:
        type: string
        description: 语言
      langLevel:
        type: string
        description: 语言水平
        enum:
          - NORMAL
          - GOOD
          - SKILLED
          - PROFICIENT
      grade:
        type: integer
        description: 年级
      stuCard:
        type: string
        description: 学生卡照片url
      certs:
        type: array
        description: 证书照片url数组
      avatar:
        type: string
        description: 头像url

  Student:
    type: object
    required: 
      - account
      - name
      - phone
    allOf: 
      - $ref: '#/definitions/BasicModel'
      - $ref: '#/definitions/AccModel'
      - $ref: '#/definitions/StudentUpdater'

  UploadResult:
    type: object
    properties:
      success:
        type: bool
        description: 是否成功
      msg:
        type: string
        description: 失败时的提示信息
      url:
        type: string
        description: 上传成功时，返回对应的url

# Errors
  Error:
    type: object
    required:
      - status
      - developerMessage
      - userMessage
    properties:
      status:
        type: string
        example: "500"
      developerMessage:
        type: string
        description: Message for developers to locate the problem.
        example: "Unkown Error."
      userMessage:
        type: string
        description: Message for the end-user.
        example: "Sorry, We have encounted an unkown error."
